// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOBicFLeDECMZ6o6vwtdDsM-wj95tWIZA',
    appId: '1:823313764710:web:28dc6351b7f8c85367b8a7',
    messagingSenderId: '823313764710',
    projectId: 'yizenotes',
    authDomain: 'yizenotes.firebaseapp.com',
    storageBucket: 'yizenotes.appspot.com',
    measurementId: 'G-TG27EB7LJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYg5IFJkiaJMd_a2NCf99WwcP9DWML2y8',
    appId: '1:823313764710:android:2b86c27f29c969e067b8a7',
    messagingSenderId: '823313764710',
    projectId: 'yizenotes',
    storageBucket: 'yizenotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK9oxGhLwh70dYFGNZBzLj7mCcBYS26yo',
    appId: '1:823313764710:ios:5cdf2a92c4295d1967b8a7',
    messagingSenderId: '823313764710',
    projectId: 'yizenotes',
    storageBucket: 'yizenotes.appspot.com',
    iosBundleId: 'com.example.Yize_Notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK9oxGhLwh70dYFGNZBzLj7mCcBYS26yo',
    appId: '1:823313764710:ios:771dd08f83b2655c67b8a7',
    messagingSenderId: '823313764710',
    projectId: 'yizenotes',
    storageBucket: 'yizenotes.appspot.com',
    iosBundleId: 'com.example.Yize_Notes.RunnerTests',
  );
}
